# -- dependencies --
apacheTikaVersion=3.3.1
ehcacheVersion=3.12.0
hypersistenceVersion=3.15.4
kotlinLoggingVersion=8.0.4
kotlinVersion=2.4.10
spotlessVersion=8.8.0
postgresVersion=42.7.13
springBootVersion=4.1.0
springCloudBootstrapVersion=5.0.2
springCloudServerVersion=5.0.2
springDependencyManagementVersion=1.1.7
springSecurityOauth2Version=7.1.0

# -- project --
group=nl.nl-portal
version=2.0.0
