spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/nl-portal
    username: nlportal
    password: password
    name: nl-portal-config-database
    hikari:
      auto-commit: false
      poolName: "gzac-portal-pool"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/auth/realms/nlportalconfig
