server:
  port: 8888

spring:
  application:
    name: configuration-panel-backend
  cache:
    type: simple
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: # env var
    username: # env var
    password: # env var
    name: nl-portal-config-database
    hikari:
      auto-commit: false
      poolName: "nl-portal-config-pool"
  liquibase:
    change-log: classpath:/liquibase/config-master.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show_sql: false
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl.auto: none
        generate_statistics: false
        naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        cache:
          use_second_level_cache: false
          use_query_cache: false
          region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        format_sql: true
        jdbc:
          time_zone: UTC
        connection:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
configuration-panel:
  cache:
    config-ttl: ${CONFIG_CACHE_TTL}
  security:
    token: ${CONFIGURATION_SERVER_TOKEN}
