name: Build and Push Docker Image
on:
    push:
        branches:
            - "main"
            - "rc/*"
            - "release/*"
env:
    GITHUB_REGISTRY: ghcr.io
    DOCKER_IMAGE_NAME: configuration-panel
    GITHUB_NAMESPACE: nl-portal
    JAVA_VERSION: "21"
    NODE_VERSION: "20.x"
jobs:
    prepare-variables:
        runs-on: ubuntu-latest
        outputs:
            scope: ${{ steps.detect-scope.outputs.SCOPE }}
            backend-tag: ${{ steps.detect-scope.outputs.SCOPE == 'RELEASE' && steps.get-project-versions.outputs.BACKEND_VERSION || steps.generate-snapshot-rc-version.outputs.BACKEND_SNAPSHOT_VERSION }}
            frontend-tag: ${{ steps.detect-scope.outputs.SCOPE == 'RELEASE' && steps.get-project-versions.outputs.FRONTEND_VERSION || steps.generate-snapshot-rc-version.outputs.FRONTEND_SNAPSHOT_VERSION }}
        steps:
            -   name: Detect scope
                id: detect-scope
                run: echo "SCOPE=$(if ${{ github.ref_name == 'main' }} ; then echo "SNAPSHOT" ; elif ${{ startsWith(github.ref_name, 'rc/') }} ; then echo "RC" ; elif ${{ startsWith(github.ref_name, 'release/') }} ; then echo "RELEASE" ; else echo "UNKNOWN" ; fi)" >> $GITHUB_OUTPUT
            -   name: Log Scope
                run: echo "::notice::Using Scope - ${{ steps.detect-scope.outputs.SCOPE }}"
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Get version from project
                id: get-project-versions
                run: |
                    echo "BACKEND_VERSION=$(grep "version" backend/gradle.properties | sed 's/^.*=//' | grep -Po '\d+\.\d+\.\d+')" >> $GITHUB_OUTPUT
                    echo "FRONTEND_VERSION=$(grep "version" frontend/package.json | grep -Po '\d+\.\d+\.\d+')" >> $GITHUB_OUTPUT
            -   name: Generate SNAPSHOT/RC Tag
                id: generate-snapshot-rc-version
                if: ${{ steps.detect-scope.outputs.SCOPE == 'SNAPSHOT' || steps.detect-scope.outputs.SCOPE == 'RC' }}
                run: |
                    be_version=${{ steps.get-project-versions.outputs.BACKEND_VERSION }}
                    fe_version=${{ steps.get-project-versions.outputs.FRONTEND_VERSION }}
                    branch=${GITHUB_REF##*/}
                    sha=${GITHUB_SHA::8}
                    ts=$(date +'%Y%m%d%H%M')
                    echo "BACKEND_SNAPSHOT_VERSION=${{ steps.detect-scope.outputs.SCOPE == 'RC' && '${be_version}-${ts}-RC' || '${branch}-${ts}-${sha}-SHAPSHOT' }}" >> "$GITHUB_OUTPUT"
                    echo "FRONTEND_SNAPSHOT_VERSION=${{ steps.detect-scope.outputs.SCOPE == 'RC' && '${fe_version}-${ts}-RC' || '${branch}-${ts}-${sha}-SHAPSHOT' }}" >> "$GITHUB_OUTPUT"
    build-be:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: "backend"
        needs:
            - prepare-variables
        if: ${{ needs.prepare-variables.outputs.scope != 'UNKNOWN' }}
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK ${{ env.JAVA_VERSION }}
                uses: actions/setup-java@v4
                with:
                    java-version: "${{ env.JAVA_VERSION }}"
                    distribution: "temurin"
            -   name: Set up gradle
                uses: gradle/actions/setup-gradle@v4
            -   name: Build with Gradle
                run: ./gradlew build
            -   name: Prepare dist folder
                run: mkdir deployment | mv build/ Dockerfile deployment/
            -   name: Archive dist folder
                uses: actions/upload-artifact@v4
                with:
                    name: configuration-panel-backend-dist
                    path: backend/deployment/
                    retention-days: 1
    build-fe:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: "frontend"
        needs:
            - prepare-variables
        if: ${{ needs.prepare-variables.outputs.scope != 'UNKNOWN' }}
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up Node.js ${{ env.NODE_VERSION }}
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ env.NODE_VERSION }}
            -   name: Install
                run: npm install -g pnpm && pnpm install
            -   name: Build
                run: pnpm build
            -   name: Prepare dist folder
                run: mkdir deployment | mv build/ conf/ entrypoint.sh Dockerfile deployment/
            -   name: Archive dist folder
                uses: actions/upload-artifact@v4
                with:
                    name: configuration-panel-frontend-dist
                    path: frontend/deployment/
                    retention-days: 1
    publish-be:
        runs-on: ubuntu-latest
        needs:
            - prepare-variables
            - build-be
        if: ${{ needs.prepare-variables.outputs.scope != 'UNKNOWN' }}
        permissions:
            contents: read
            packages: write
            id-token: write
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    fetch-depth: 1

            -   name: Install Cosign
                uses: sigstore/cosign-installer@v3.5.0

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Download dist artifact
                uses: actions/download-artifact@v4
                with:
                    name: configuration-panel-backend-dist

            -   name: 'Login to github packages'
                uses: docker/login-action@v1
                with:
                    registry: ${{ env.GITHUB_REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Log Tag
                run: echo "::notice::Using backend tag - ${{ needs.prepare-variables.outputs.backend-tag }}"

            -   id: docker_meta
                uses: docker/metadata-action@v5
                with:
                    images: ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}-backend
                    tags: |
                        type=raw,value=latest,enable={{is_default_branch}}
                        type=raw,value=${{ needs.prepare-variables.outputs.backend-tag }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@v6
                id: build-and-push
                with:
                    file: Dockerfile
                    platforms: linux/arm64, linux/amd64
                    context: .
                    push: true
                    tags: ${{ steps.docker_meta.outputs.tags }}
                    labels: ${{ steps.docker_meta.outputs.labels }}

            -   name: Sign the images with GitHub OIDC Token
                env:
                    DIGEST: ${{ steps.build-and-push.outputs.digest }}
                    TAGS: ${{ steps.docker_meta.outputs.tags }}
                run: |
                    images=""
                    for tag in ${TAGS}; do
                      images+="${tag}@${DIGEST} "
                    done
                    cosign sign --yes ${images}

            -   name: Verify the images
                run: |
                    branch=${GITHUB_REF##*/}
                    cosign verify ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ needs.prepare-variables.outputs.image-tag }} \
                       --certificate-identity https://github.com/${{ env.GITHUB_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}/.github/workflows/cicd.yaml@refs/heads/${branch} \
                       --certificate-oidc-issuer https://token.actions.githubusercontent.com | jq
    publish-fe:
        runs-on: ubuntu-latest
        needs:
            - prepare-variables
            - build-fe
        if: ${{ needs.prepare-variables.outputs.scope != 'UNKNOWN' }}
        permissions:
            contents: read
            packages: write
            id-token: write
        steps:
            -   name: Install Cosign
                uses: sigstore/cosign-installer@v3.5.0

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Download dist artifact
                uses: actions/download-artifact@v4
                with:
                    name: configuration-panel-frontend-dist

            -   name: Display structure of downloaded files
                run: pwd && ls -R

            -   name: 'Login to github packages'
                uses: docker/login-action@v1
                with:
                    registry: ${{ env.GITHUB_REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Log Tag
                run: echo "::notice::Using frontend tag - ${{ needs.prepare-variables.outputs.frontend-tag }}"

            -   id: docker_meta
                uses: docker/metadata-action@v5
                with:
                    images: ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}-frontend
                    tags: |
                        type=raw,value=latest,enable={{is_default_branch}}
                        type=raw,value=${{ needs.prepare-variables.outputs.frontend-tag }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@v6
                id: build-and-push
                with:
                    file: Dockerfile
                    platforms: linux/arm64, linux/amd64
                    context: .
                    push: true
                    tags: ${{ steps.docker_meta.outputs.tags }}
                    labels: ${{ steps.docker_meta.outputs.labels }}

            -   name: Sign the images with GitHub OIDC Token
                env:
                    DIGEST: ${{ steps.build-and-push.outputs.digest }}
                    TAGS: ${{ steps.docker_meta.outputs.tags }}
                run: |
                    images=""
                    for tag in ${TAGS}; do
                      images+="${tag}@${DIGEST} "
                    done
                    cosign sign --yes ${images}

            -   name: Verify the images
                run: |
                    branch=${GITHUB_REF##*/}
                    cosign verify ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ needs.prepare-variables.outputs.image-tag }} \
                       --certificate-identity https://github.com/${{ env.GITHUB_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}/.github/workflows/cicd.yaml@refs/heads/${branch} \
                       --certificate-oidc-issuer https://token.actions.githubusercontent.com | jq
